### ISSUE TITLE
React will show warning in console when app run in development.

### ISSUE THREAD

**Issue by sherlockkong** [lo-tp/material-ui-pagination#2]
I fond this, 
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

Could you please fix this issue in your code?
Thanks.

**Comment by lo-tp** [comment]
Hi @sherlockkong 

The warning is caused by the breaking change of react 16.0.
I've corrected my own code to make it meet the new best practice promoted by facebook in  pr #3.
Unluckily, the warning is not totally eliminated due to dependencies such as **material-ui**(Maybe they are still using the old fashion `React.propTypes`).
I wonder if you have any idea on how to clear the warnings caused by these dependencies?

Best Wishes

**Comment by sherlockkong** [comment]
Hi, lo-tp

Great, Thanks for your update.
I'm using material-ui-pagination by npm, could you please update the npm package too? 

>>Unluckily, the warning is not totally eliminated due to dependencies such as material-ui(Maybe they are still using the old fashion React.propTypes).I wonder if you have any idea on how to clear the warnings caused by these dependencies?

I'm using the {  "material-ui": "^0.18.0" }, but no warning will show in console. 

Thanks
Sherlock

**Comment by lo-tp** [comment]
@sherlockkong 
Cheers. I've upload the updated version to npm.

**Comment by sherlockkong** [comment]
Great. Thank you.

**Comment by sherlockkong** [comment]
Hi lo-tp.
Unfortunately, The warning still will show in console if I use material-ui-pagination npm package.

Thanks
Sherlock

**Comment by lo-tp** [comment]
Hi @sherlockkong ,
Sorry to hear that.
I have no idea if there is any other thing I can do to help you out.
I would be very grateful if any clue was given about how to solve this.

**Comment by lo-tp** [comment]
Hi @sherlockkong 
Credits go to @BenjaVR , Now the warning is perfectly cleared.
Try upgrade to version 1.03.

**Comment by sherlockkong** [comment]
@lo-tp 
Great, thanks.
