### ISSUE TITLE
Component issue

### ISSUE THREAD

**Issue by vostramedia** [lo-tp/material-ui-pagination#7]
What does the following do?
`import Component from '../dist/index';`

This is not documented properly. What is Component and where is it coming from?

**Comment by lo-tp** [comment]
Sorry for the confusion caused by the snippet in the readme( which is updated now).

`import Component from '../dist/index'`, the purpose of this is to import the **pagination** component.

'../dist/index' is a relative path, you'll understand this easily once you build the project with `yarn build` and check the resulted file structure.
